name: lookbook

on:
  workflow_dispatch:
  schedule:
     - cron: '2 2-16/4 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build1:
    env:
      duilie: 1
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}


    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install -g npm
          npm update
      - name: '运行 【book1】'
        run: |
          node Task/book.js
        env:
          duilie: 1
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


  build2:
    env:
      duilie: 2
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}


    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install -g npm
          npm update
      - name: '运行 【book2】'
        run: |
          node Task/book.js
        env:
          duilie: 2
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
